config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :companies_services
  resources :contacts
  resources :phones
  resources :memberships
  resources :companies
  devise_for :users

  root to: "companies#index"
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates :amount, :expires_on, presence: true

  belongs_to :company
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    respond_to do |format|
      if @membership.destroy
        format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to memberships_url, alert: @membership.errors.full_messages }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:amount, :amount_paid, :paid_at, :expires_on, :company_id)
    end
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>

  <%= f.label company %>
  <%= f.text_field company %>

  <%= f.label amount %>
  <%= f.text_field amount %>

  <%= f.label expires_on %>
  <%= f.text_field expires_on %>

  <%= f.label amount_paid %>
  <%= f.text_field amount_paid %>

  <%= f.label paid_at %>
  <%= f.text_field paid_at %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing Memberships</h1>

<table>
  <thead>
    <tr>
      <th><%= Membership.human_attribute_name(:company) %></th>
      <th><%= Membership.human_attribute_name(:amount) %></th>
      <th><%= Membership.human_attribute_name(:expires_on) %></th>
      <th><%= Membership.human_attribute_name(:amount_paid) %></th>
      <th><%= Membership.human_attribute_name(:paid_at) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.company %></td>
        <td><%= membership.amount %></td>
        <td><%= membership.expires_on %></td>
        <td><%= membership.amount_paid %></td>
        <td><%= membership.paid_at %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<%= membership.company %>
<%= membership.amount %>
<%= membership.expires_on %>
<%= membership.amount_paid %>
<%= membership.paid_at %>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>