config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :companies_services
  resources :contacts
  resources :phones
  resources :memberships
  resources :companies
  devise_for :users

  root to: "companies#index"
end

app/models/companies_service.rb
class CompaniesService < ActiveRecord::Base
  validates :company, :services, :expected_send_date, presence: true
  belongs_to :company
  belongs_to :service
end

app/controllers/companies_services_controller.rb
class CompaniesServicesController < ApplicationController
  before_action :set_companies_service, only: [:show, :edit, :update, :destroy]

  # GET /companies_services
  # GET /companies_services.json
  def index
    @companies_services = CompaniesService.all
  end

  # GET /companies_services/1
  # GET /companies_services/1.json
  def show
  end

  # GET /companies_services/new
  def new
    @companies_service = CompaniesService.new
  end

  # GET /companies_services/1/edit
  def edit
  end

  # POST /companies_services
  # POST /companies_services.json
  def create
    @companies_service = CompaniesService.new(companies_service_params)

    respond_to do |format|
      if @companies_service.save
        format.html { redirect_to @companies_service, notice: 'Companies service was successfully created.' }
        format.json { render :show, status: :created, location: @companies_service }
      else
        format.html { render :new }
        format.json { render json: @companies_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies_services/1
  # PATCH/PUT /companies_services/1.json
  def update
    respond_to do |format|
      if @companies_service.update(companies_service_params)
        format.html { redirect_to @companies_service, notice: 'Companies service was successfully updated.' }
        format.json { render :show, status: :ok, location: @companies_service }
      else
        format.html { render :edit }
        format.json { render json: @companies_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies_services/1
  # DELETE /companies_services/1.json
  def destroy
    @companies_service.destroy
    respond_to do |format|
      format.html { redirect_to companies_services_url, notice: 'Companies service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companies_service
      @companies_service = CompaniesService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def companies_service_params
      params[:companies_service]
    end
end

app/views/companies_services/_form.html.erb
<%= form_for(@companies_service) do |f| %>
  <% if @companies_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@companies_service.errors.count, "error") %> prohibited this companies_service from being saved:</h2>

      <ul>
      <% @companies_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies_services/edit.html.erb
<h1>Editing Companies Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @companies_service %> |
<%= link_to 'Back', companies_services_path %>

app/views/companies_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies Services</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies_services.each do |companies_service| %>
      <tr>
        <td><%= link_to 'Show', companies_service %></td>
        <td><%= link_to 'Edit', edit_companies_service_path(companies_service) %></td>
        <td><%= link_to 'Destroy', companies_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Companies service', new_companies_service_path %>

app/views/companies_services/new.html.erb
<h1>New Companies Service</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_services_path %>

app/views/companies_services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_companies_service_path(@companies_service) %> |
<%= link_to 'Back', companies_services_path %>